# Generated by Django 4.0.3 on 2024-09-05 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_scrap_created_at_alter_scrap_post_alter_scrap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scraps',
            field=models.ManyToManyField(related_name='scrapped_posts', through='posts.Scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
